apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: external-secrets-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: external-secrets-controller
    app.kubernetes.io/part-of: external-secrets
  name: external-secrets-controllfriy
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: external-secrets-controller
    weight: 100
status: {}
