apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: external-secrets-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: external-secrets-controller
    app.kubernetes.io/part-of: external-secrets
  name: external-secrets-controller
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: external-secrets-controller
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: external-secrets-controller
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-gitops-tenant/external-secrets/external-secrets-controller@sha256:74c9d1b9c821049174dab77d5160deac005764cbe0434e9de2df1f91a98f7514
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
